# These are supported funding model platforms

github: dsamithmendis
patreon: dsamithmendis
open_collective:
ko_fi:
tidelift:
community_bridge:
liberapay:
issuehunt:
lfx_crowdfunding:
polar:
buy_me_a_coffee:
thanks_dev:
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
